sudo: true
dist: bionic
language: cpp
cache: ccache
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
        - libomp-dev
    env:
      - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
before_install:
- eval "${MATRIX_EVAL}"
- export DETECTOR_INSTALL=$TRAVIS_BUILD_DIR/install
install:
script:
- cd $TRAVIS_BUILD_DIR
- mkdir build
- cd build
- cmake -DCMAKE_INSTALL_PREFIX=$DETECTOR/install -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_FLAGS=$CPP_CXX_FLAGS -DCMAKE_EXE_LINKER_FLAGS=$CPP_LINKER_FLAGS  ..
- make
- make install
